### ISSUE TITLE
Incompatible with PolyMC.

### ISSUE THREAD

**Issue by RDKRACZ** [Pepperoni-Jabroni/MapAtlases#4] opened 2021-01-27 14:34 UTC
https://github.com/TheEpicBlock/PolyMc
With polymc the atlas GUI looks like this
![image](https://user-images.githubusercontent.com/43277609/106006023-16097e00-60b5-11eb-84f3-8feed1fad59b.png)

**Comment by Pepperoni-Jabroni** [comment] 2021-01-29 06:45
Is PolyMC known to work with mods that have completely custom Screens (& ScreenHandlers)? If not, I'm gonna file this as a won't-fix because the issue is likely on their end, not mine.

**Comment by FewerFlaws** [comment] 2021-02-06 22:47
Looks to me like a failure here is expected behaviour due to the [current state of PolyMC's development](https://theepicblock.github.io/PolyMc/status.html)

**Comment by Pepperoni-Jabroni** [comment] 2021-02-06 22:59
Thanks @FewerFlaws for providing a link! Closing this out.

**Closed** 2021-02-06 22:59 UTC
